---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: opstree
type: Opaque
data: # all below values are not actual, they are base64 encoded, and for db url which is connection string of mongodb encode in base64 within single quotes '<url>' 
  CLOUDINARY_CLOUD_NAME: ZGp1OHdmemRj
  CLOUDINARY_KEY: MzY2MzIxNzQ2MTYxODUy
  CLOUDINARY_SECRET: Vmd6aXJ2VERybXM2TGhPOE9adXJHWTdNdlZ3
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhM0pwZEdocGEyRXhJaXdpWVNJNkltTnRPR2x1TldVME9EQmxOV2N5YW5GNWJURm9NelJxTm1raWZRLmFtLTNSSjFXQndKZlRDTk9iLVVJb3c=
  # Below is of Local In Private Subnet
  DB_URL: bW9uZ29kYjovL0plbmtpbnM6amVua2luczEyM0AxOTIuMTY4LjExOS4xMzk6MjcwMTcvWWVscERiP2F1dGhzb3VyY2U9TXlEYg==
  # Below is of Atlas
  #DB_URL: bW9uZ29kYitzcnY6Ly9rcml0aGlrYXNoYXJtYTIxMjk6bnZhdU9idFA1V0Jxd2ZKY0Btb25nb2RiY2x1c3RlcjAuNnA2eDcubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPU1vbmdvREJDbHVzdGVyMA==
  SECRET: YW55c2VjcmV0dGV4dA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: opstree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: krithikasharma/nodejscamp:v1
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: opstree
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
