---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data: # all below values are not actual, they are base64 encoded, and for db url which is connection string of mongodb encode in base64 within single quotes '<url>' 
  CLOUDINARY_CLOUD_NAME=ZGp1OHdmemRjCg==
  CLOUDINARY_KEY=MzY2MzIxNzQ2MTYxODUyCg==
  CLOUDINARY_SECRET=Vmd6aXJ2VERybXM2TGhPOE9adXJHWTdNdlZ3Cg==
  MAPBOX_TOKEN=cGsuZXlKMUlqb2lhM0pwZEdocGEyRXhJaXdpWVNJNkltTnRPR2x1TldVME9EQmxOV2N5YW5GNWJU
  Rm9NelJxTm1raWZRLmFtLTNSSjFXQndKZlRDTk9iLVVJb3cK
  DB_URL=bW9uZ29kYitzcnY6Ly9rcml0aGlrYXNoYXJtYTIxMjk6bnZhdU9idFA1V0Jxd2ZKY0Btb25nb2Ri
  Y2x1c3RlcjAuNnA2eDcubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZh
  cHBOYW1lPU1vbmdvREJDbHVzdGVyMAo=
  SECRET=YW55c2VjcmV0dGV4dAo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: krithikasharma/nodejscamp:v1
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
